app.constant('STATS', {
  home: 'home',
  homeSlider: 'homeSlider@home',
  homeproducts: 'homeproducts@home',
  homeTopRatedItem: 'homeTopRatedItem@home',
  homeFeaureItem: 'homeFeaureItem@home',
  homeRecentView: 'homeRecentView@home',
  user: 'user',
  userLogin: 'user.login',
  userSighup: 'user.sighup',
  product: 'product',
  productView: 'product.view',
  productReview: 'product.review',
  cart: 'cart',
  checkout: 'checkout',
  checkoutLogin: 'checkout.login',
  checkoutSignup: 'checkout.signup',
  checkoutAddress: 'checkout.address',
  checkoutPayment: 'checkout.payment',

  dashboard: 'dashboard',
  dashboardViewUser: 'dashboard.viewUser',
  dashboardOrders: 'dashboard.orders',
  dashboardOrderView: 'dashboard.orderView',
  dashboardProducts: 'dashboard.products',
  dashboardProductView: 'dashboard.productView',
  });
