app.constant('URLS', {
  baseUrl: '/rest',
  productUrl: '/products',
  proeuctDeleteUrl: '/products/delete/',
  productSearchUrl: '/products/search',
  productUpdateUrl: '/products/update',
  productCreateUrl: '/products/create',
  productUploadImage: '/products/uploadImage',
  productRecommUrl: 'products/findProductRecomm',
  departmentUrl: '/dept',
  departmentSearchUrl: '/dept/search',
  categoryUrl: '/category/:id',
  cartUrl: '/cart',
  addToCartUrl: '/cart/addToCart/',
  updateCartUrl: '/cart/update/',
  cartItemDelete: '/cart/deleteItem/',
  userUrl: '/user',
  userSearch: '/user/search',
  userProfileUrl: '/user/profile',
  updateShippingDetailUrl : '/checkout/updateShippingDetail/',
  findAllUsersUrl: '/user/findAllUsers/',
  findAllSuppliersUrl: '/supplier/findAllSuppliers/',
  userActionUrl: '/user/action/',
  userDeleteUrl: '/user/delete/',
  userCreateUrl: '/user/create',
  userUpdateUrl: '/user/update',
  userChangePasswordUrl: '/user/changePassword/',
  supplierActionUrl: '/supplier/action/',
  supplierDeleteUrl: '/supplier/delete/',
  placeOrderUrl: '/order/placeOrder/',

  orderSearchUrl: '/order/search',
  orderByUserIdUrl: '/order/findByUserId/',
  orderUpdateUrl: '/order/update',

  reviewSearchUrl: "/review/search",
  
});

